.TH ADB 1 "29 September 2011"
.SH NAME
adb \- android debug bridge
.SH SYNOPSIS
.B adb
[
.I options
]
.I command
.LP
.SH DESCRIPTION
.LP
.B adb
allows one to interact with a connected Android device.

.SH COMMANDS
.TP
.BR help
Show help message and a list of commands.

.SH SEE ALSO
For documentation for the latest version visit:

https://developer.android.com/tools/help/adb.html
